openapi-library/OpenAPIValidators

package.json

forgot to update the Patch version during #9, which we need to do because that was a bug fix and we'll be rereleasing

update version number for #9

---

lib/resValidator.js
test/unit/setup.test.js

I discovered that our errors were displayed as `Error: Error: <msg>`.
This displays them simply as `Error: <msg>`.

Remove unnecessary error prefix

---

lib/resValidator.js
package.json
test/exampleOpenApiFiles/valid/openapi3.yml
test/unit/assertions/satisfyApiSpec.test.js

Previously, if the user's OpenAPI doc defined a `/test` path, and their server responded with a `res.req.path` of `'/test?exampleQueryParam=foo'`, we would not recognise that the two pathnames were the same.
This PR fixes that and adds a test case proving it.
(Aside from that, much of the diff is just indentation)

Fix bug when res.req has query param

---

README.md
lib/resValidator.js
package.json
test/exampleOpenApiFiles/valid/openapi3.json
test/exampleOpenApiFiles/valid/openapi3.yml
test/unit/assertions/satisfyApiSpec.test.js
test/unit/assertions/usingServer.test.js

Adds support and tests for multiple servers in OpenAPI 3 spec.
This has changed the tests so that some are now disabled for OpenAPI 2 specs - I'm not sure if this is the best way to do it or if there's a better solution.

Add support for multiple servers defined in the OpenAPI spec

---

lib/classes/BaseOpenApiSpec.js
lib/classes/OpenApi2Spec.js
lib/classes/OpenApi3Spec.js
lib/classes/Response.js
lib/index.js
lib/openApiSpecFactory.js
stryker.conf.js

Makes code clearer and easier to maintain/extend
* use `OpenApiSpec` classes instead of pure functions
* put code unique to OpenAPI 2 in new `OpenApi2Spec` class, and same for OpenAPI 3
* add links to official OpenAPI docs
* increase strictness of mutation testing

refactor: split code into OpenApiSpec classes

---

lib/classes/BaseOpenApiSpec.js
lib/classes/OpenApi2Spec.js
lib/classes/OpenApi3Spec.js
lib/classes/Response.js
stryker.conf.js
test/resources/exampleOpenApiFiles/valid/serversDefinedDifferently/noServersProperty.yml
test/resources/exampleOpenApiFiles/valid/serversDefinedDifferently/noServersWithBasePaths.yml
test/resources/exampleOpenApiFiles/valid/serversDefinedDifferently/onlyAbsoluteServersWithBasePaths.yml
test/resources/exampleOpenApiFiles/valid/serversDefinedDifferently/serversIsEmptyArray.yml
test/resources/exampleOpenApiFiles/valid/serversDefinedDifferently/variousServers.yml
test/unit/assertions/definedServerPath.test.js
test/unit/assertions/differentRequestModules.test.js
test/unit/assertions/satisfyApiSpec.test.js

For https://github.com/RuntimeTools/chai-openapi-response-validator/issues/30. (Also extends https://github.com/RuntimeTools/chai-openapi-response-validator/issues/17).
Should support the 'Server URL Format' and 'Relative URLs' sections of https://swagger.io/docs/specification/api-host-and-base-path/. We do not yet support 'Server Templating' or 'Overriding Servers'
Should satisfy [description of 'servers' field in OpenAPI 3 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields)

User can define complex relative and absolute servers in OpenAPI 3 spec

---

.eslintrc.yml
.travis.yml
package-lock.json
package.json

As https://github.com/RuntimeTools/chai-openapi-response-validator/issues/30#issuecomment-566078318 shows, Windows developers should be able to run this project. 
I don't have a Windows machine but these changes allowed `npm run test:full` to succeed on a Windows 10 WM and also the Travis builds.
Changes:
* added travis job to build and test on windows with every PR
* removed eslint rule that errored on windows (linebreak-style), which does not seem necessary now that we are testing both macos and windows on travis (could test linux too, but I'm assuming testing macos is enough)
* upgraded nyc version because the current version was erroring on windows. See https://github.com/istanbuljs/nyc/issues/1205#issuecomment-552124764

Windows developer can run tests for this project

---

lib/classes/BaseOpenApiSpec.js
lib/classes/Response.js
test/resources/exampleApp.js
test/resources/exampleOpenApiFiles/valid/openapi3.yml
test/unit/assertions/differentRequestModules.test.js

for https://github.com/RuntimeTools/chai-openapi-response-validator/issues/29.
* resolves the case described in https://github.com/RuntimeTools/chai-openapi-response-validator/issues/29#issuecomment-567064245, which affected superagent-based request packages and request-promise
* improves testing around our 4 supported request packages

feat: support string responses with text/html header

---

README.md
lib/index.js
lib/openApiSpecFactory.js
package-lock.json
package.json
test/unit/setup.test.js

Part of https://github.com/RuntimeTools/chai-openapi-response-validator/issues/31: allows user to load api spec like this:
```js
before(async() => {
const apiSpec = (await axios.get('url/to/openapi/spec')).data;
chai.use(chaiResponseValidator(apiSpec)); // no need to write out to a file
}
```
Also:
* minor clarification of test blocks
* minor corrections to the README

User can define api spec directly as object

---

.editorconfig

E.g. in VSCode [this extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) will read the .editorconfig file and automatically apply the correct editor settings

chore: add .editorconfig to simplify dev setup

---

.eslintrc.yml
README.md
lib/classes/BaseOpenApiSpec.js
lib/classes/OpenApi2Spec.js
lib/classes/OpenApi3Spec.js
lib/classes/Response.js
lib/index.js
test/resources/exampleOpenApiFiles/valid/satisfySchemaInApiSpec/openapi2.json
test/resources/exampleOpenApiFiles/valid/satisfySchemaInApiSpec/openapi3.yml
test/unit/assertions/satisfyApiSpec.test.js
test/unit/assertions/satisfySchemaInApiSpec.test.js

for https://github.com/RuntimeTools/chai-openapi-response-validator/issues/38
* see the updated README for what feature this PR adds.
* corrects a tiny mistake in the docs (`string` -> `stringProperty`)
Note the comment about how I've implemented the validation:
```
* I don't know how to validate objects against schemas directly.
* So I put the object inside a mock response, then validate
* the whole response against a mock expected response.
* The 2 mock responses are identical except for the body,
* thus validating the object against its schema.
```
The only package I found allowing us to validate the object directly (rather than validating an entire response object) was [swagger-model-validator](https://github.com/swagger-model-validator/swagger-model-validator). 
However, this did not …

feat: user can validate objects against individual schemas

---

package-lock.json
package.json

Resolves #38 
Features:
* Users can now validate objects against individual schema objects https://github.com/RuntimeTools/chai-openapi-response-validator/issues/38, e.g.:
Given an API spec including:
```
...
components:
schemas:
ExampleSchemaObject:
type: string
...
```
Assert in unit tests:
```js
expect('foo').to.satisfySchemaDefinedInApiSpec('ExampleSchemaObject') // passes
expect(['foo']).to.satisfySchemaDefinedInApiSpec('ExampleSchemaObject') // throws useful error 
```
For a fuller guide, see docs from [master](https://github.com/RuntimeTools/chai-openapi-response-validator#in-unit-tests-validate-objects-against-schemas-defined-in-your-OpenAPI-spec) or [the original PR](https://github.com/RuntimeTools/chai-openapi-response-validator/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8 …

Release 0.7.0

---

AUTHORS.md
lib/classes/Response.js
test/resources/exampleApp.js
test/resources/exampleOpenApiFiles/valid/openapi2.json
test/resources/exampleOpenApiFiles/valid/openapi3.yml
test/unit/assertions/differentRequestModules.test.js
test/unit/assertions/satisfyApiSpec.test.js

This is a proposed resolution to: 
https://github.com/RuntimeTools/chai-openapi-response-validator/issues/49
The (this.res.body) falsey check is failing for potentially valid falsey values (false, null), returning 'undefined' for non-axios request providers.

Alter body retrieval to '=== undefined' for response-provider checks

---

lib/classes/Response.js
test/unit/assertions/differentRequestModules.test.js

When https://github.com/RuntimeTools/chai-openapi-response-validator/issues/49 was fixed we only checked that we correctly validated falsy response bodies when making requests with chai-http.
It turns out that we were incorrectly validating `null` response bodies when making requests with request-promise.
[When an Express server responds with `res.json(null)`, the response has header `application/json` and the body is JSON.stringified to `'null'`](https://expressjs.com/en/api.html#res.json). Other request modules seem to treat these response bodies as null, but request-promise treats this response body (most accurately) as `'null'`. 
Therefore we were forcing users who did this to say in the OpenAPI spec that their response body is a string. But I think users want to say instead that …

fix, test: correctly validate stringified null res.body for request-promise

---

lib/classes/Response.js
test/resources/exampleApp.js
test/resources/exampleOpenApiFiles/valid/openapi3.yml
test/unit/assertions/differentRequestModules.test.js

This PR _fixes https://github.com/RuntimeTools/chai-openapi-response-validator/issues/54 (pending release) by correctly validating responses from Express servers responding via:
* `res.sendStatus(204)`
* `res.status(204).send()`
* `res.status(204).end`
* `res.status(204).json()`
The code checks whether the response has a `content-type` header (and whether the body actually seems to have content).
Notes
1. If your server responds via `res.status(200).json()`, the `content-type` header is `text/plain`. https://expressjs.com/en/api.html#res.json says this is accurate (`res.json` should set a content-type header) but we can change the code if to suit users. 
2. Strictly speaking, https://expressjs.com/en/api.html#res.sendStatus says `res.sendStatus` sends the string representation of the …

fix: correctly validate responses without bodies

---

package-lock.json
package.json

Features:
* Some TypeScript support! Added a TypeScript Declaration File so you can use this plugin in TypeScript projects without running in type errors https://github.com/RuntimeTools/chai-openapi-response-validator/issues/61. See [usage guide](https://github.com/RuntimeTools/chai-openapi-response-validator#using-this-plugin-in-a-typescript-project)
* Changed some negated assertions to pass instead of fail https://github.com/RuntimeTools/chai-openapi-response-validator/pull/67
`expect(res).to.not.satisfyApiSpec` used to mean "expect `res` to *match but not satisfy* a response defined in your API spec". 
now `expect(res).to.not.satisfyApiSpec` means "expect `res` to *neither match nor satisfy* a response defined in your API spec". 
So if `res` matches no responses in your API spec, then …

Release 0.8.0

---

AUTHORS.md
packages/jest-openapi/index.d.ts

The default function was missing in the Typescript declarations for jest-openapi (similar to #61 which is fixed by these [two lines](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/index.d.ts#L25)).
This fixes #73.

fix: add jestOpenAPI function export to type declaration file

---

packages/jest-openapi/src/index.js

**Describe the bug**
When using another test runner (such as mocha) with Jest expect, you have to manually set Jest as the global expect. This means that global expect has to be set when this library is imported, rather than when the library is used.
```
const jestExpect = require('expect')
global.expect = jestExpect
```
**To Reproduce**
https://github.com/BenGu3/jest-openapi-validator-bug
**Expected behavior**
The library verifies that `global.expect` exists when the init function is called, not when the library is imported.

fix: pull jest expect off global when function is called

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json

**jest-openapi**
fix:
* correct jest-openapi type declaration file https://github.com/RuntimeTools/OpenAPIValidators/pull/74
* make jest-openapi easier to use in test runners other than Jest #76

release 0.9.2

---

packages/chai-openapi-response-validator/test/assertions/satisfyApiSpec/differentRequestModules.test.js

We were accidentally testing `supertest` when we should have been testing `request-promise`! This improves coverage and explains why `RequestPromiseReponse.js` uses `replace` on the `res.body`, which is relevant to https://github.com/RuntimeTools/OpenAPIValidators/pull/81#issuecomment-636326923

test: fix RequestPromise test

---

commonTestResources/exampleOpenApiFiles/valid/openapi2.json
commonTestResources/exampleOpenApiFiles/valid/openapi3.yml
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/AbstractResponse.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/AxiosResponse.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/RequestPromiseResponse.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/SuperAgentResponse.js
packages/chai-openapi-response-validator/package.json
packages/chai-openapi-response-validator/stryker.conf.js
packages/chai-openapi-response-validator/test/assertions/satisfyApiSpec/satisfyApiSpec.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/toSatisfyApiSpec.test.js
packages/jest-openapi/src/openapi-validator/lib/classes/AbstractResponse.js
packages/jest-openapi/src/openapi-validator/lib/classes/AxiosResponse.js
packages/jest-openapi/src/openapi-validator/lib/classes/RequestPromiseResponse.js
packages/jest-openapi/src/openapi-validator/lib/classes/SuperAgentResponse.js
yarn.lock

This renables mutation tests in the PR build, and restores the mutation score of `chai-openapi-response-validator` to nearly 100%. 
The mutation tests were skipped while `stryker`'s subdependency `run-async`'s subdependency `is-promise` was broken. I've updated our version of `run-async`, which no longer uses `is-promise`
There are 4 mutants remaining. I'm happy to leave the first 3 because they are about error cases that I don't know how to test usefully. The 4th should be killed when we complete https://github.com/RuntimeTools/OpenAPIValidators/issues/57
```
153. [Survived] StringLiteral
/Users/richard.waller@ibm.com/Documents/Projects/SideProjects/OpenApiChai/OpenAPIValidators/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/AbstractOpenApiSpec.js:138:8
- …
```

test: renable mutation tests

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json

fix:
* support request-promise returning parsed json https://github.com/RuntimeTools/OpenAPIValidators/pull/74 @ludeknovy 
chore(deps):
* updated openapi-response-validator to ^4.0.0 (was ^3.8.2) https://github.com/RuntimeTools/OpenAPIValidators/pull/79 @mvegter

release 0.9.3

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json
yarn.lock

Reverts RuntimeTools/OpenAPIValidators#96 as it messes up our tests by running the sampleApp on port 5000 before the previous test has shut it down. E.g.:
https://travis-ci.com/github/RuntimeTools/OpenAPIValidators/builds/169840896
Not sure how to fix this, but for now I will keep @stryker-mutator at 3.1.0, and Mocha at 7.1.1

Revert "chore(deps-dev): bump @stryker-mutator/core from 3.1.0 to 3.2.4"

---

packages/chai-openapi-response-validator/package.json
yarn.lock

Reverts https://github.com/RuntimeTools/OpenAPIValidators/pull/94 as it messes up our tests by running the sampleApp on port 5000 before the previous test has shut it down. See https://github.com/RuntimeTools/OpenAPIValidators/pull/104
Probably due to Issue 4234 in mocha 7.2.0: https://github.com/mochajs/mocha/releases

chore(deps-dev): lower mocha from 7.2.0 to 7.1.1

---

packages/chai-openapi-response-validator/package.json
packages/chai-openapi-response-validator/stryker.conf.js
yarn.lock

Reverts https://github.com/RuntimeTools/OpenAPIValidators/pull/105, which reverted https://github.com/RuntimeTools/OpenAPIValidators/pull/94
I realised mocha 7.2.0 made our stryker mutation tests throw those annoying port `listen EADDRINUSE` errors only because (I think) mocha 7.2.0 enables stryker to run mocha tests concurrently. By forcing the `maxConcurrentTestRunners` to be 1, the tests using ports should not conflict with each other

chore(deps-dev): bump mocha from 7.1.1 to 7.2.0

---

commonTestResources/exampleOpenApiFiles/valid/preferNonTemplatedPathOverTemplatedPath/nonTemplatedPathAfterTemplatedPath/openapi2.yml
commonTestResources/exampleOpenApiFiles/valid/preferNonTemplatedPathOverTemplatedPath/nonTemplatedPathAfterTemplatedPath/openapi3.yml
commonTestResources/exampleOpenApiFiles/valid/preferNonTemplatedPathOverTemplatedPath/nonTemplatedPathBeforeTemplatedPath/openapi2.yml
commonTestResources/exampleOpenApiFiles/valid/preferNonTemplatedPathOverTemplatedPath/nonTemplatedPathBeforeTemplatedPath/openapi3.yml
packages/chai-openapi-response-validator/lib/assertions/satisfyApiSpec.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi2Spec.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi3Spec.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/utils.js
packages/chai-openapi-response-validator/package.json
packages/chai-openapi-response-validator/test/assertions/satisfyApiSpec/preferNonTemplatedPathOverTemplatedPath.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/preferNonTemplatedPathOverTemplatedPath.test.js
packages/jest-openapi/src/matchers/toSatisfyApiSpec.js
packages/jest-openapi/src/openapi-validator/lib/classes/OpenApi2Spec.js
packages/jest-openapi/src/openapi-validator/lib/classes/OpenApi3Spec.js
packages/jest-openapi/src/openapi-validator/lib/utils.js

solves https://github.com/RuntimeTools/OpenAPIValidators/issues/57 using design discussed here: https://github.com/RuntimeTools/OpenAPIValidators/issues/57#issuecomment-609005781

fix(57): support multiple routes of same resource

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json

fix:
* request paths should match non-templated OpenAPI paths over templated OpenAPI paths https://github.com/RuntimeTools/OpenAPIValidators/pull/107 @rwalle61

release 0.9.4

---

packages/chai-openapi-response-validator/lib/assertions/satisfyApiSpec.js
packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi2Spec.js
packages/chai-openapi-response-validator/test/assertions/satisfyApiSpec/differentRequestModules.test.js
packages/chai-openapi-response-validator/test/assertions/satisfyApiSpec/specsDefineServersDifferently.test.js
packages/chai-openapi-response-validator/test/assertions/satisfySchemaInApiSpec/satisfySchemaInApiSpec.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/differentRequestModules.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/specsDefineBasePathDifferently.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/specsDefineServersDifferently.test.js
packages/jest-openapi/__test__/matchers/toSatisfyApiSpec/toSatisfyApiSpec.test.js
packages/jest-openapi/__test__/matchers/toSatisfySchemaInApiSpec/toSatisfySchemaInApiSpec.test.js
packages/jest-openapi/package.json
packages/jest-openapi/src/matchers/toSatisfyApiSpec.js
packages/jest-openapi/src/matchers/toSatisfySchemaInApiSpec.js
packages/jest-openapi/src/openapi-validator/lib/classes/OpenApi2Spec.js
packages/jest-openapi/src/openapi-validator/lib/classes/OpenApi3Spec.js
packages/jest-openapi/src/openapi-validator/lib/utils.js
packages/jest-openapi/src/utils.js

* feat: support OpenAPI 2 basePath (https://github.com/RuntimeTools/OpenAPIValidators/pull/172)
* test: remove invalid test cases (https://github.com/RuntimeTools/OpenAPIValidators/pull/185)
* refactor: general tidy (https://github.com/RuntimeTools/OpenAPIValidators/pull/185)
* chore: drop unused dependency (compress-tag)

feat, test, refactor(jest): port openapi2 basepath support etc.

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json

feat:
* support OpenAPI 2 basePaths https://github.com/RuntimeTools/OpenAPIValidators/pull/172 @tgiardina & https://github.com/RuntimeTools/OpenAPIValidators/pull/186 @rwalle61 
* (minor) add extra newline in error message https://github.com/RuntimeTools/OpenAPIValidators/pull/185 https://github.com/RuntimeTools/OpenAPIValidators/pull/186 @rwalle61
test:
* we dropped a few invalid test cases, which should not affect any users https://github.com/RuntimeTools/OpenAPIValidators/pull/185 https://github.com/RuntimeTools/OpenAPIValidators/pull/186 @rwalle61

chore: release 0.10.0

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json

chore:
* switch license from Apache to MIT https://github.com/openapi-library/OpenAPIValidators/pull/211 @rwalle61

chore: release 0.11.0

---

packages/chai-openapi-response-validator/package.json
packages/jest-openapi/package.json
packages/openapi-validator/package.json

No functional changes expected. Code common to the chai and jest plugins is now published as a separate npm package ([openapi-validator](https://www.npmjs.com/package/openapi-validator)). The chai and jest plugins list it as a dependency in their `package.json`s
refactor:
* move openapi-validator to yarn workspace https://github.com/openapi-library/OpenAPIValidators/pull/220 @rwalle61 & https://github.com/openapi-library/OpenAPIValidators/pull/191 @mvegter

chore: release 0.12.0

---

.travis.yml
README.md
packages/chai-openapi-response-validator/README.md
packages/jest-openapi/README.md

Complete migrating away from Travis (started in https://github.com/openapi-library/OpenAPIValidators/commit/3702417578dc939ba3cbd9e2ae0a9cdeba2e8a82)

ci: finish replacing Travis with GitHub Actions

---

lerna.json
package.json
yarn.lock

Going to try lerna out before:
- generating a changelog
- auto-publishing to npm
- auto-generating a GitHub release
Sticking with `yarn workspaces run *` because `lerna run *` strips colours from the output

ci: use lerna to manage versions

---

packages/openapi-validator/package.json

fix: move `@types/request` and `@types/superagent` to `dependencies`

---

packages/openapi-validator/package.json

for https://github.com/openapi-library/OpenAPIValidators/issues/258

fix: fix TS lib check by exporting type deps as prod deps
